# Default values for opencensus-collector-app.
# This is a YAML-formatted file.

replicaCount: 1

image:
  registry: quay.io
  image: giantswarm/opencensus-collector
  tag: 0.1.11
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceType: ClusterIP

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 512Mi

enableOpencensusReceiver: true
enableZipkinReceiver: true
enableJaegerReceiver: true

ports:
  opencensusReceiver: 55678
  zipkinReceiver: 9411
  jaegerReceiverTChannel: 14267
  jaegerReceiverHTTP: 14268

jaegerURL: http://jaeger.tracing:14268/api/traces

annotateNamespaceForLinkerd: false

kubectlImage:
  registry: quay.io
  name: giantswarm/docker-kubectl
  tag: 933ac043b7bec33104aac58b16849ea28bace26c
  pullPolicy: IfNotPresent
