# Default values for opencensus-collector-app.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: omnition
  image: opencensus-collector
  tag: 0.1.11
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 512Mi
