version: 2.1
orbs:
  architect: giantswarm/architect@0.8.5

jobs:
  run_kat_tests:
    machine:
      image: ubuntu-1604:201903-01
    working_directory:
      ~/giantswarm-todo
    steps:
      - checkout
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}-<< pipeline.git.tag >>
      - restore_cache:
          key: v2-python-cache-{{ checksum "test/kind/Pipfile.lock" }}
      - run: curl -Lo /tmp/kind-app-testing.sh -q https://github.com/giantswarm/kind-app-testing/raw/master/kind-app-testing.sh
      - run: chmod +x /tmp/kind-app-testing.sh
      - run: mkdir /tmp/bin || true
      - restore_cache:
          key: bin-{{ checksum "/tmp/kind-app-testing.sh" }}
      - run: if [[ ! -f /tmp/bin/kind ]]; then curl -Lo /tmp/bin/kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64" && chmod +x /tmp/bin/kind; fi
      - run: if [[ ! -f /tmp/bin/helm ]]; then curl -Lo /tmp/helm.tar.gz https://get.helm.sh/helm-v2.16.5-linux-amd64.tar.gz && tar zxf /tmp/helm.tar.gz -C /tmp && mv /tmp/linux-amd64/helm /tmp/bin/helm; fi
      - run: if [[ ! -f /tmp/bin/kubectl ]]; then curl -Lo /tmp/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl && chmod +x /tmp/bin/kubectl; fi
      - save_cache:
          key: bin-{{ checksum "/tmp/kind-app-testing.sh" }}
          paths:
            - /tmp/bin
      - run: /tmp/bin/helm init -c
      - run: PATH="/tmp/bin:$PATH" /tmp/kind-app-testing.sh -c opencensus-collector-app
      - run: sudo chown -R circleci.circleci /tmp/kat
      - save_cache:
          key: v2-python-cache-{{ checksum "test/kind/Pipfile.lock" }}
          paths:
            - /tmp/kat/.local
            - /tmp/kat/.cache
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results


workflows:
  version: 2
  build:
    jobs:
      - run_kat_tests:
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          name: "package and push opencensus-collector-app chart"
          requires:
            - run_kat_tests
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "opencensus-collector-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/