version: 2.1
orbs:
  architect: giantswarm/architect@dev:kat-test

workflows:
  version: 2
  build:
    jobs:
      - architect/run-kat-tests:
          name: "test with kat opencensus-collector-app chart"
          chart: "opencensus-collector-app"
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          name: "package and push opencensus-collector-app chart"
          requires:
            - architect/run-kat-tests:
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "opencensus-collector-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
