version: 2.1
orbs:
  architect: giantswarm/architect@0.6.0

workflows:
  push-to-app-catalog:
    jobs:
      - architect/push-to-app-catalog:
          name: "package and push chart to app catalog"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "opencensus-collector-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
