---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencensus-collector-app.fullname" . }}-conf
  labels:
{{ include "opencensus-collector-app.labels" . | indent 4 }}
data:
  oc-collector-config: |
    receivers:
      opencensus:
        port: 55678
        keepalive:
          server-parameters:
            max-connection-age: 120s
            max-connection-age-grace: 30s            
      zipkin:
        port: 9411
      jaeger: {}
    queued-exporters:
      jaeger:
        num-workers: 4
        queue-size: 100
        retry-on-failure: true
        sender-type: jaeger-thrift-http
        jaeger-thrift-http:
          collector-endpoint: http://jaeger.tracing:14268/api/traces
          timeout: 5s
