---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencensus-collector-app.fullname" . }}-conf
  labels:
{{ include "opencensus-collector-app.labels" . | indent 4 }}
data:
  oc-collector-config: |
    receivers:
{{- if .Values.enableOpencensusReceiver }}
      opencensus:
        port: {{ .Values.ports.opencensusReceiver }}
        keepalive:
          server-parameters:
            max-connection-age: 120s
            max-connection-age-grace: 30s
{{- end }}
{{- if .Values.enableZipkinReceiver }}
      zipkin:
        port: {{ .Values.ports.zipkinReceiver }}
{{- end }}
{{- if .Values.enableJaegerReceiver }}
      jaeger:
        jaeger-thrift-tchannel-port: {{ .Values.ports.jaegerReceiverTChannel }}
        jaeger-thrift-http-port: {{ .Values.ports.jaegerReceiverHTTP }}
{{- end }}
    queued-exporters:
      jaeger:
        num-workers: 4
        queue-size: 100
        retry-on-failure: true
        sender-type: jaeger-thrift-http
        jaeger-thrift-http:
          collector-endpoint: {{ .Values.jaegerURL }}
          timeout: 5s
