apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencensus-collector-app.fullname" . }}
  labels:
{{ include "opencensus-collector-app.labels" . | indent 4 }}
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "opencensus-collector-app.labels" . | indent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
      labels:
{{ include "opencensus-collector-app.labels" . | indent 8 }}
    spec:
      containers:
      - command:
          - "/occollector_linux"
          - "--config=/conf/oc-collector-config.yaml"
        env:
        - name: GOGC
          value: "80"
        name: {{ .Chart.Name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.image }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        ports:
{{- if .Values.enableOpencensusReceiver }}
        - containerPort: {{ .Values.ports.opencensusReceiver }}
{{- end }}
{{- if .Values.enableJaegerReceiver }}
        - containerPort: {{ .Values.ports.jaegerReceiverTChannel }}
        - containerPort: {{ .Values.ports.jaegerReceiverHTTP }}
{{- end }}
{{- if .Values.enableZipkinReceiver }}
        - containerPort: {{ .Values.ports.zipkinReceiver }}
{{- end }}
        volumeMounts:
        - name: oc-collector-config-vol
          mountPath: /conf
#        - name: oc-collector-secrets
#          mountPath: /secrets
        livenessProbe:
          httpGet:
            path: /
            port: 13133
        readinessProbe:
          httpGet:
            path: /
            port: 13133
      volumes:
        - configMap:
            name: {{ include "opencensus-collector-app.fullname" . }}-conf
            items:
              - key: oc-collector-config
                path: oc-collector-config.yaml
          name: oc-collector-config-vol
#        - secret:
#            name: oc-collector-secrets
#            items:
#              - key: cert.pem
#                path: cert.pem
#              - key: key.pem
#                path: key.pem
