apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Release.Name }}-oc-collector-psp
  labels:
{{ include "opencensus-collector-app.labels" . | indent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
  readOnlyRootFilesystem: false
  allowedCapabilities:
    - NET_ADMIN
    - NET_RAW
  requiredDropCapabilities:
    - ALL
  fsGroup:
    rule: MustRunAs
    ranges:
    - max: 65535
      min: 1
  runAsGroup:
    rule: MustRunAs
    ranges:
    - max: 65535
      min: 1
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  runAsUser:
{{- if .Values.linkerdEnabled }}
    rule: RunAsAny
{{- else }}
    rule: MustRunAsNonRoot
{{- end }}
  seLinux:
    rule: RunAsAny
  volumes:
  - secret
  - emptyDir
  - configMap
  - projected
  - downwardAPI
