---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "opencensus-collector-app.fullname" . }}
  labels:
{{ include "opencensus-collector-app.labels" . | indent 4 }}
roleRef:
  kind: Role
  name: {{ include "opencensus-collector-app.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "opencensus-collector-app.fullname" . }}