---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "opencensus-collector-app.fullname" . }}
  labels:
{{ include "opencensus-collector-app.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
  resourceNames: 
  - {{ include "opencensus-collector-app.fullname" . }}-conf 
