---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencensus-collector-app.fullname" . }}
  labels:
{{ include "opencensus-collector-app.labels" . | indent 4 }}
spec:
  ports:
  - name: opencensus
    port: 55678
    protocol: TCP
    targetPort: 55678
#  - name: jaeger-tchannel
#    port: 14267
#  - name: jaeger-thrift-http
#    port: 14268
#  - name: zipkin
#    port: 9411
  selector:
{{ include "opencensus-collector-app.labels" . | indent 4 }}
