---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencensus-collector-app.fullname" . }}
  labels:
{{ include "opencensus-collector-app.labels" . | indent 4 }}
spec:
  serviceType: {{ .Values.serviceType }}
  ports:
{{- if .Values.enableOpencensusReceiver }}
  - name: opencensus
    port: {{ .Values.ports.opencensusReceiver }}
    protocol: TCP
    targetPort: {{ .Values.ports.opencensusReceiver }}
{{- end }}
{{- if .Values.enableJaegerReceiver }}
  - name: jaeger-tchannel
    port: {{ .Values.ports.jaegerReceiverTChannel }}
  - name: jaeger-thrift-http
    port: {{ .Values.ports.jaegerReceiverHTTP }}
{{- end }}
{{- if .Values.enableZipkinReceiver }}
  - name: zipkin
    port: {{ .Values.ports.zipkinReceiver }}
  selector:
{{- end }}
{{ include "opencensus-collector-app.labels" . | indent 4 }}
